# Generated by Django 4.1.3 on 2022-11-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_productcategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, unique=True, verbose_name="имя"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="короткое описание"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="цена"
                    ),
                ),
                (
                    "price_with_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="цена со скидкой",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество на складе"
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="products_images")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mainapp.productcategory",
                    ),
                ),
            ],
        ),
    ]
